/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1;

/**
 *
 * @author josue
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        Servicios servicio =new Servicios();
        servicio.setServicios();
    }
    //creacion de variable globales
    public static int contador=0;
    public static int correlativo=0;
    public static int largo=0;
    public static String clientes[][]= new String[5][3];
    public static String cuentas[][]=new String[25][4];
    public static String servicios[][]=new String[3][2];
    public static String historial[][]=new String[500][7];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        menuMain = new javax.swing.JMenuBar();
        menuCrear = new javax.swing.JMenu();
        menuCrearCliente = new javax.swing.JMenuItem();
        menuItemCrearCuenta = new javax.swing.JMenuItem();
        menuVerClientes = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        menuVerHistorial = new javax.swing.JMenuItem();
        menuDepositar = new javax.swing.JMenu();
        menuDepositarACuenta = new javax.swing.JMenuItem();
        menuTransferencia = new javax.swing.JMenuItem();
        menuPagoDeServicios = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        menuMain.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        menuCrear.setText("Crear");
        menuCrear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCrearMouseClicked(evt);
            }
        });

        menuCrearCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuCrearCliente.setText("Crear cliente");
        menuCrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCrearClienteMouseClicked(evt);
            }
        });
        menuCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearClienteActionPerformed(evt);
            }
        });
        menuCrear.add(menuCrearCliente);

        menuItemCrearCuenta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuItemCrearCuenta.setText("Crear cuenta");
        menuItemCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearCuentaActionPerformed(evt);
            }
        });
        menuCrear.add(menuItemCrearCuenta);

        menuMain.add(menuCrear);

        menuVerClientes.setText("Ver");
        menuVerClientes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        menuClientes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuClientes.setText("Ver clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuVerClientes.add(menuClientes);

        menuVerHistorial.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuVerHistorial.setText("Historial");
        menuVerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerHistorialActionPerformed(evt);
            }
        });
        menuVerClientes.add(menuVerHistorial);

        menuMain.add(menuVerClientes);

        menuDepositar.setText("Acciones");
        menuDepositar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        menuDepositarACuenta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuDepositarACuenta.setText("Depositar a cuenta");
        menuDepositarACuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepositarACuentaActionPerformed(evt);
            }
        });
        menuDepositar.add(menuDepositarACuenta);

        menuTransferencia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuTransferencia.setText("Transferencia entre cuentas");
        menuTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransferenciaActionPerformed(evt);
            }
        });
        menuDepositar.add(menuTransferencia);

        menuPagoDeServicios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuPagoDeServicios.setText("Pago de servicios");
        menuPagoDeServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagoDeServiciosActionPerformed(evt);
            }
        });
        menuDepositar.add(menuPagoDeServicios);

        menuMain.add(menuDepositar);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //llamada de formularios
    private void menuCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearClienteActionPerformed
        new frmCrearCliente().setVisible(true);  
    }//GEN-LAST:event_menuCrearClienteActionPerformed

    private void menuItemCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearCuentaActionPerformed
        new frmCrearCuenta().setVisible(true);
    }//GEN-LAST:event_menuItemCrearCuentaActionPerformed

    private void menuPagoDeServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagoDeServiciosActionPerformed
        new frmAccionesPagoServicios().setVisible(true);
    }//GEN-LAST:event_menuPagoDeServiciosActionPerformed

    private void menuCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCrearMouseClicked
            
    }//GEN-LAST:event_menuCrearMouseClicked

    private void menuCrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCrearClienteMouseClicked
            // TODO add your handling code here:
    }//GEN-LAST:event_menuCrearClienteMouseClicked

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        new frmVerClientes().setVisible(true);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuDepositarACuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepositarACuentaActionPerformed
        new frmAccionesDepositar().setVisible(true);
    }//GEN-LAST:event_menuDepositarACuentaActionPerformed

    private void menuTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransferenciaActionPerformed
        new frmAccionesTransferir().setVisible(true);
    }//GEN-LAST:event_menuTransferenciaActionPerformed

    private void menuVerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerHistorialActionPerformed
        new frmVerHistorial().setVisible(true);
    }//GEN-LAST:event_menuVerHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        frmMenu frame = new frmMenu();
        frame.setTitle("Menu");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenu menuCrear;
    private javax.swing.JMenuItem menuCrearCliente;
    private javax.swing.JMenu menuDepositar;
    private javax.swing.JMenuItem menuDepositarACuenta;
    private javax.swing.JMenuItem menuItemCrearCuenta;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenuItem menuPagoDeServicios;
    private javax.swing.JMenuItem menuTransferencia;
    private javax.swing.JMenu menuVerClientes;
    private javax.swing.JMenuItem menuVerHistorial;
    // End of variables declaration//GEN-END:variables
}
